
management:
  endpoints:
    web:
      exposure:
        include:
          - info
#          - env
#          - beans
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
  source:
    target: "@java.version@"
    encoding: "@project.build.sourceEncoding@"

node:
  name: node01
  id: local:${node.name}
