
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - loggers
  endpoint:
    health:
      show-details: always
      show-components: always

node:
  name: node01
  id: local:${node.name}
